from enum import Enum


class Event(Enum):
	ARGS = 'ARGS'
	VALIDATE = 'VALIDATE'
	PERM = 'PERM'
	PRE = 'PRE'
	ON = 'ON'
	EXTN = 'EXTN'
	SOFT = 'SOFT'
	DIFF = 'DIFF'
	SYS_DOCS = 'SYS_DOCS'


class DELETE_STRATEGY(Enum):
	SOFT_SKIP_SYS = 'DELETE_SOFT_SKIP_SYS'
	SOFT_SYS = 'DELETE_SOFT_SYS'
	FORCE_SKIP_SYS = 'DELETE_FORCE_SKIP_SYS'
	FORCE_SYS = 'DELETE_FORCE_SYS'


class LIMP_VALUES(Enum):
	NONE_VALUE = 'NONE_VALUE'
